use Mix.Config

import_config "dev_open_id_providers.exs"
# import_config "proxies.exs"
config :excyte, env: :dev

# Configure your database
config :excyte, Excyte.Repo,
  username: "postgres",
  password: "postgres",
  database: "excyte_dev",
  hostname: "localhost",
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with webpack to recompile .js and .css sources.
config :excyte, ExcyteWeb.Endpoint,
  http: [port: 4000],
  https: [
      port: 4001,
      cipher_suite: :strong,
      certfile: "priv/cert/selfsigned.pem",
      keyfile: "priv/cert/selfsigned_key.pem"
    ],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: [
    node: [
      "node_modules/webpack/bin/webpack.js",
      "--mode",
      "development",
      "--watch",
      cd: Path.expand("../assets", __DIR__)
    ]
  ]

config :ex_twilio,
  account_sid: System.get_env("TWILIO_ACCOUNT_SID"),
  api_key: System.get_env("TWILIO_API_KEY"),
  api_secret: System.get_env("TWILIO_API_SECRET")

config :excyte, :aws, %{
  access_key_id: System.get_env("AWS_ACCESS_KEY_ID"),
  secret_access_key: System.get_env("AWS_SECRET_ACCESS_KEY"),
  host: "s3.amazonaws.com",
  region: "us-west-1"
}

config :mux,
  access_token_id: System.get_env("MUX_ACCESS_TOKEN"),
  access_token_secret: System.get_env("MUX_SECRET_KEY"),
  signing_secret: System.get_env("MUX_SIGNING_SECRET")


config :excyte, Excyte.Mailer, adapter: Bamboo.LocalAdapter
config :stripity_stripe, api_key: System.get_env("STRIPE_SECRET")
config :excyte, :stripe_signing_secret, System.get_env("STRIPE_SIGNING_SECRET")
config :excyte, :base_url, System.get_env("EXCYTE_URL")
config :excyte, :realtor_rapid_api_key, System.get_env("REALTOR_RAPID_API")
config :excyte, :us_real_estate_rapid_api_key, System.get_env("US_REAL_ESTATE_RAPID_API")
config :excyte, :bridge_server_key, System.get_env("BRIDGE_SERVER_KEY")

config :excyte, :agent_plans, [
  %{
    name: "Monthly",
    id: "month",
    price: "24.95",
    default: true,
    stripe_id: "price_1JGYHDJYg86TDWnAe4zUaQPb",
    trial_period: 30
  }, %{
    name: "Yearly",
    id: "year",
    price: "249.95",
    default: false,
    stripe_id: "price_1JGYHDJYg86TDWnAHZ0w9z74",
    trial_period: 30
  }
]

config :excyte, :brokerage_plans, [
  %{
    name: "10 - 20 Agents",
    max_agent_count: 20,
    order: 1,
    id: "twenty",
    price: "199.95",
    default: true,
    stripe_id: "price_1JH4vqJYg86TDWnAWVtBgBjh",
    trial_period: 30
  }, %{
    name: "20 - 30 Agents",
    max_agent_count: 30,
    order: 2,
    id: "thirty",
    price: "299.95",
    default: false,
    stripe_id: "price_1JH4vqJYg86TDWnAqyHZK6L4",
    trial_period: 30
  }, %{
    name: "30 - 40 Agents",
    max_agent_count: 40,
    order: 3,
    id: "forty",
    price: "399.95",
    default: false,
    stripe_id: "price_1JH4vqJYg86TDWnARzGeKxAP",
    trial_period: 30
  }, %{
    name: "40 - 50 Agents",
    max_agent_count: 50,
    order: 4,
    id: "fifty",
    price: "499.95",
    default: false,
    stripe_id: "price_1JH4vqJYg86TDWnATXtsb1wy",
    trial_period: 30
  }
]


# config :excyte, :twilio_numbers, System.get_env("TWILIO_NUMBERS") |> File.read!()
# config :excyte, env: "#{Mix.env()}"

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :excyte, ExcyteWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/excyte_web/.*/(live|controllers)/.*(ex)$",
      ~r"lib/excyte_web/.*/.*(ex)$",
      ~r"lib/excyte_web/.*/templates/.*(leex|eex)$"
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
