import Config

import_config "open_id_providers.exs"
config :excyte, env: :prod

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :excyte, ExcyteWeb.Endpoint,
  url: [host: System.get_env("RENDER_EXTERNAL_HOSTNAME") || "localhost", port: 80],
  cache_static_manifest: "priv/static/cache_manifest.json"

config :excyte, :aws, %{
  access_key_id: System.get_env("AWS_ACCESS_KEY_ID"),
  secret_access_key: System.get_env("AWS_SECRET_ACCESS_KEY"),
  host: "s3.amazonaws.com",
  region: "us-west-1"
}

config :mux,
  access_token_id: System.get_env("MUX_ACCESS_TOKEN"),
  access_token_secret: System.get_env("MUX_SECRET_KEY"),
  signing_secret: System.get_env("MUX_SIGNING_SECRET")

config :excyte, :agent_plans, [
  %{
    name: "Monthly",
    id: "month",
    price: "24.95",
    default: true,
    stripe_id: "price_1JGXyPJYg86TDWnARMsIvm7P",
    trial_period: 30
  }, %{
    name: "Yearly",
    id: "year",
    price: "249.95",
    default: false,
    stripe_id: "price_1JGXyPJYg86TDWnAbwqMzEdG",
    trial_period: 30
  }
]

config :excyte, :brokerage_plans, [
  %{
    name: "10 - 20 Agents",
    max_agent_count: 20,
    order: 1,
    id: "twenty",
    price: "199.95",
    default: true,
    stripe_id: "price_1JH5JTJYg86TDWnAiCRVoNGk",
    trial_period: 30
  }, %{
    name: "20 - 30 Agents",
    max_agent_count: 30,
    order: 2,
    id: "thirty",
    price: "299.95",
    default: false,
    stripe_id: "price_1JH5JTJYg86TDWnApdxUqlCy",
    trial_period: 30
  }, %{
    name: "30 - 40 Agents",
    max_agent_count: 40,
    order: 3,
    id: "forty",
    price: "399.95",
    default: false,
    stripe_id: "price_1JH5JTJYg86TDWnASrEPV9TD",
    trial_period: 30
  }, %{
    name: "40 - 50 Agents",
    max_agent_count: 50,
    order: 4,
    id: "fifty",
    price: "499.95",
    default: false,
    stripe_id: "price_1JH5JUJYg86TDWnAaWIa9xbZ",
    trial_period: 30
  }
]

config :excyte, :base_url, System.get_env("EXCYTE_URL")
config :excyte, :bridge_server_key, System.get_env("BRIDGE_SERVER_KEY")
# Do not print debug messages in production
config :logger, level: :info

# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to the previous section and set your `:url` port to 443:
#
#     config :excyte, ExcyteWeb.Endpoint,
#       ...
#       url: [host: "example.com", port: 443],
#       https: [
#         port: 443,
#         cipher_suite: :strong,
#         keyfile: System.get_env("SOME_APP_SSL_KEY_PATH"),
#         certfile: System.get_env("SOME_APP_SSL_CERT_PATH"),
#         transport_options: [socket_opts: [:inet6]]
#       ]
#
# The `cipher_suite` is set to `:strong` to support only the
# latest and more secure SSL ciphers. This means old browsers
# and clients may not be supported. You can set it to
# `:compatible` for wider support.
#
# `:keyfile` and `:certfile` expect an absolute path to the key
# and cert in disk or a relative path inside priv, for example
# "priv/ssl/server.key". For all supported SSL configuration
# options, see https://hexdocs.pm/plug/Plug.SSL.html#configure/1
#
# We also recommend setting `force_ssl` in your endpoint, ensuring
# no data is ever sent via http, always redirecting to https:
#
#     config :excyte, ExcyteWeb.Endpoint,
#       force_ssl: [hsts: true]
#
# Check `Plug.SSL` for all available options in `force_ssl`.

# Finally import the config/prod.secret.exs which loads secrets
# and configuration from environment variables.
