import Config

import_config "open_id_providers.exs"
config :excyte, env: :staging

config :excyte,
        whitelist: [
          "derek+agent@excyte.io",
          "derek+brokerage@excyte.io",
          "gary+agent@excyte.io",
          "gary+brokerage@excyte.io"
        ]

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
secret_key_base =
  System.get_env("SECRET_KEY_BASE") ||
    raise """
    environment variable SECRET_KEY_BASE is missing.
    You can generate one by calling: mix phx.gen.secret
    """

config :excyte, ExcyteWeb.Endpoint,
  http: [
    port: String.to_integer(System.get_env("PORT") || "4000"),
    transport_options: [socket_opts: [:inet6]]
  ],
  url: [
    scheme: "https",
    host: "excyte.io",
    port: 443
  ],
  server: true,
  check_origin: [
    "//excyte.io",
    "//www.excyte.io",
    "//staging.excyte.io",
    "//excytecma.com",
    "//www.excytecma.com",
    "//staging.excytecma.com",
    "//excyte-re.onrender.com",
    "https://localhost:4000",
    "https://excyte.ngrok.io"
  ],
  secret_key_base: secret_key_base,
  pubsub_server: Excyte.PubSub

config :ex_twilio,
  account_sid: System.get_env("TWILIO_ACCOUNT_SID"),
  api_key: System.get_env("TWILIO_API_KEY"),
  api_secret: System.get_env("TWILIO_API_SECRET")

config :ex_aws,
  access_key_id: System.get_env("AWS_ACCESS_KEY_ID"),
  secret_access_key: System.get_env("AWS_SECRET_ACCESS_KEY"),
  host: "s3.amazonaws.com",
  region: "us-west-1"

config :mux,
  access_token_id: System.get_env("MUX_ACCESS_TOKEN"),
  access_token_secret: System.get_env("MUX_SECRET_KEY"),
  signing_secret: System.get_env("MUX_SIGNING_SECRET")

config :excyte, :agent_plans, "prod_JuMhdzU3j59SFc"
config :excyte, :brokerage_plans, "prod_Juv9tYtNIvrWdC"

config :stripity_stripe, api_key: System.get_env("STRIPE_SECRET")
config :excyte, :stripe_signing_secret, System.get_env("STRIPE_SIGNING_SECRET")
config :excyte, :base_url, System.get_env("EXCYTE_URL")
config :excyte, :realtor_rapid_api_key, System.get_env("REALTOR_RAPID_API")
config :excyte, :us_real_estate_rapid_api_key, System.get_env("US_REAL_ESTATE_RAPID_API")
config :excyte, :bridge_server_key, System.get_env("BRIDGE_SERVER_KEY")
# Do not print debug messages in production
config :logger, level: :info
